### ISSUE TITLE
stat: big data interface support

### ISSUE THREAD

**Issue by jonlawlor** [gonum/stat#29]
I've been thinking about how samples and weighted samples are represented in `stat`, and in `dist`, in the `ConjugateUpdate` methods, and it seems like we might be able to do something interesting by providing a set of interfaces to represent different ways of providing sample data to measure.

Here's the rough outline:

``` go
type Sampler interface {
   Sample() []float64
}

type WeightedSampler interface {
   Sampler
   Weights() []float64
}

type Sample []float64

func (s Sample) Sample() []float64 {
   return s
}

type WeightedSample struct {
   Sample
   w []float64
}

func NewWeightedSample(s Sample, w []float64) *WeightedSample {
   // panic if len doesn't match
  return &WeightedSample{s, w}
}

func (ws *WeightedSample) Weights() []float64 {
  return ws.w
}
```

And then collapse functions like `Mean` to take a `Sampler`, perform a type check to see if it is a `WeightedSampler`, and then proceed from there.

This also ties into iterative methods where the data cannot be represented in memory easily.  We could provide:

``` go
type SampleReader interface {
   SampleRead([]float64) int
}
// and equivalent with weights

type IterativeSample func([]float64) int 

func (is IterativeSample) SampleRead(buf []float64) int {
   return is(buf)
}

func (is IterativeSample) Sample() []float64 {
   buf := make([]float64, 1023)
   res := make([]float64, 0)
   for n := is(buf); n > 0; {
      res = append(res, buf...)
   }
   return res // for use in cases where a SampleReader path doesn't exist
}
```

Which could read a portion of the sample in things like `Mean`.  There would be a corresponding `WeightedIterativeSampler`, and additional types for multivariate samples, which would deal primarily in matrices.  There is still some planning to do to allow things like buffered reading and writing.

The same types would be used in `dist` for `ConjugateUpdate`, `Rand`, and equivalent ones would exist in a multivariate version of `dist`.

Online versions of the various statistical measurements would take only a `SampleReader` or `WeightedSampleReader`, and would have "Memory" so that they could produce updated measurements on demand.  Parallel methods could use several goroutines to call SampleRead(), and then combine the results at the end.

Any thoughts on these changes?  The immediate benefit would be to simplify the signatures for functions on samples of data, and to provide a way for users to handle very large amounts of data.

edit: fix go code

**Comment by jonlawlor** [comment]
This is what Mean would look like:

```go
// Mean computes the weighted mean of the sample data set.
//  sum_i {w_i * x_i} / sum_i {w_i}
func Mean(s Sampler) float64 {
	switch samp := s.(type) {
	case WeightedSampleReader:
		x := make([]float64, 1024)
		w := make([]float64, 1024)
		var n, m float64
		for nx, nw := samp.SampleRead(x), samp.WeightRead(w); nx > 0 || nw > 0; nx, nw = samp.SampleRead(x), samp.WeightRead(w) {
			if nx != nw {
				panic("stat: slice length mismatch")
			}
			var sx float64
			sz := n
			for i := 0; i < nx; i++ {
				sx += w[i] * x[i]
				sz += w[i]
			}
			m = m*(n/sz) + sx/sz
			n = sz
		}
		return m

	case SampleReader:
		x := make([]float64, 1024)
		var n, m float64
		for nx := samp.SampleRead(x); nx > 0; nx = samp.SampleRead(x) {
			sz := n + float64(nx)
			m = m*(n/sz) + floats.Sum(x[0:nx])/sz
			n = sz
		}
		return m

	case WeightedSampler:
		x := samp.Sample()
		w := samp.Weights()
		var (
			sumValues  float64
			sumWeights float64
		)
		for i, wts := range w {
			sumValues += wts * x[i]
			sumWeights += wts
		}
		return sumValues / sumWeights

	default:
		x := s.Sample()
		return floats.Sum(x) / float64(len(x))

	}
}
```

**Comment by btracey** [comment]
I think this sort of suggestion is better suited for gonum-dev.

This seems overcomplicated to me. The nice thing about the current function signatures is that they are simple. Most of them only use the native types in go, and with the possible exception of allowing "nil" for the weights, you can correctly infer the behavior of the function by looking at the function signature. 

With the interface changes you suggest, the function signature is actually more complicated. The user a  sees a "Sampler" input, and needs to learn what that means. This isn't sufficient, because the actual behavior is that it can accept a WeightedSampler, a SampleReader, or a WeightedSampleReader, all which the user will need to learn before using, and none of which is clear from the actual arguments to the function. Furthermore, it doesn't gain much. Yes, you can avoid a single parameter in the signature in the simple case, but you have to do extra combining in the other case. It's not clear from reading code what the behavior is; stat.Mean(x,nil) is very clearly unweighted, while stat.Mean(s) could mean lots of different things with this behavior. Lastly, while the gain for out-of-memory sets is nice, this seems like the wrong place to support it. Someone could provide a "bigstat" package that has the interfaces you suggest, and acts as a wrapper around the simple stat functions. This keeps the intended uses separate and clear.

**Comment by jonlawlor** [comment]
I agree with your assessment, so I don't think it is necessary to bring it to the mailing list for now.  It would be better to put this into a bigstat package. Online algorithms would go there as well, because much of the code would be in common.  There would have to be good documentation explaining the various Sampler interfaces.

**Comment by btracey** [comment]
Is there anyone that we know wants to use this feature? There are lots of existing solutions for basic statistics that work pretty well for very large datasets (hadoop, sql, etc.). It seems like bigstat belongs as a third-party package, at least until we know the use cases and how much we want to support them.

**Comment by kortschak** [comment]
Please take this to gonum-dev before proceeding.

**Comment by jonlawlor** [comment]
For the online algorithms, I want it, but there isn't any current use for it.  There is a clear application when dealing with large volumes of financial data.  I doubt that's the only one, but the relationship between various prices consumed in very large quantities calls for both linear algebra and bounded memory approaches.

I'm not sure I would call hadoop or sql a solution to this particular problem - they're both a lot more and a bit less.  There would always be an impedance between them and go.  They typically require an infrastructure (although something like sqllte avoids most of it).  And while they *can* produce model output such as regression coefficients, sample means, etc., it isn't really a strength, particularly when you consider multivariate problems.

I should come up with a list of things I want to work on, so that I can see what would fit into gonum and what would be better on its own.  Up until now I've been just fiddling around and pursuing ideas as they occur to me.  I'm hoping to have some more time soon - in the last few month's I've had a birth, a death, almost done buying a house, and it is a busy time for work.

**Comment by jonlawlor** [comment]
@kortschak, I will when I have something with a little more substance.

**Comment by btracey** [comment]
I definitely don't deny the utility of algorithms that work for large datasets. Only some problems are map/reducable and having ways to deal with that is important. However, it seems to me the hard part of the problem is dealing with moving the data. How do you access it from storage? How much do you cache? How much do you do with that data before discarding it? Once those questions are answered, it seems like it's a trivial wrapper around Stat. In other words, a wrapper around Mean that takes a data stream may only be marginally useful as the user may want to compute the mean, variance, and keep track of the minimum and maximum values. Those computations are trivial compared to the I/O. In this case, the composition solution is to have a "data database" package that provides sql wrappers (or whatever) that give you a WeightedSampleReader, we already provide the tools to do computation on a []float64, and then the user writes the glue code that specifies what to do with the individual slices while they're there.

Congrats on the baby and the house!

**Comment by jonlawlor** [comment]
My current thinking is that making Reader and Writer-like interfaces like those in io is going to be the best way to handle the separation of concerns.  The "data database" side would have to implement SampleWrite, etc. methods.  There would be room for intermediate functionality like caches which implement both Readers and Writers, similar to bufio. That's just a guess though, based on trying to imitate the core libs.

**Comment by btracey** [comment]
I feel similarly to before. I don't deny the utility, but I think it should be a different package or a wrapper around stat.

**Comment by sbinet** [comment]
FYI, I believe parts of the original intent are covered by my `go-hep/hbook` package:

- [godoc.org/go-hep.org/x/hep/hbook#H1D](https://godoc.org/go-hep.org/x/hep/hbook#H1D)
