### ISSUE TITLE
proposal: reorganise stat/...

### ISSUE THREAD

**Issue by kortschak** [gonum/stat#91]
I think that stat/... probably warrant a reorganisation.

The central change is to split stat into stat, univariate and multivariate. univariate and multivariate would hold their respective functions and types and stat would hold common functions and types.

In addition, dist and sample would be renamed to have the suffix uv for univariate.

The decision about which packages current stat functions/types end up in is reasonably straightforward for multivariate, but univariate vs stat may be more contentious.

Here is my initial view - only things I have an opinion on are marked. Please change with an associated comment so we get this right.

stat:
- Histogram
- SortWeighted
- CumulantKind

univariate:

multivariate:
- CorrelationMatrix
- CovarianceMatrix
- PrincipalComponents

Edit: Checklist removed to prevent rendering in issues list. This can be resurrected if/when we decide to tackle this again.

**Comment by btracey** [comment]
How about statuv and statmv instead of "univariate" and "multivariate". It keeps the global context much clearer.

**Comment by kortschak** [comment]
I dislike the stutter that you get from stat/statuv (mirroring the same issue with stat/stattest that has been proposed previously).

**Comment by jonlawlor** [comment]
I think it is a good idea to rename.  How about something shorter, like stat/uv and stat/mv ?

**Comment by kortschak** [comment]
Yeah, I was considering uv and mv. mv has an unfortunate homoglyph though.

The decision on contents needs input as well.

**Comment by btracey** [comment]
I'll admit I don't see the distinctions between stat, mv, and uv. I had thought originally that it was just breaking stat into functions that are univariate and multivariate. In that case it seems like statmv and statuv work well. I'm not concerned about the stutter as it happens in the import and not the code. However, I see that you propose stat, multi and uni. Is there a rough rule of thumb in your mind what sorts of things would go into stat? Is it like matrix where it's just stuff that would need to need to be in multiple packages?

**Comment by btracey** [comment]
Where I'm going is I wonder if they need to be different packages at all. distuv and distmv should be different. They implement things with a lot of common names but different signatures. Same thing with sampleuv and samplemv. So far it has not felt to me like there has been a similar tension in stat. Things like mean are easily implementable as a for loop and don't need a multivariate version necessarily.

My problem with multivariate and univariate is that they don't contain any information about what the package is. I would much rather have stutter than have a vague package name. stat/test does not follow this because the package implements tests, so it's fine. univariate is way too vague for what the package actually is.

**Comment by kortschak** [comment]
>Is it like matrix where it's just stuff that would need to need to be in multiple packages?

Yes.

>Where I'm going is I wonder if they need to be different packages at all.

Maybe we should leave this for some time.

**Comment by btracey** [comment]
Perhaps. I do think the name changes to distuv and distmv (and other associated) are good. It makes them feel at the same "heirarchy" level.

**Comment by btracey** [comment]
I think we fixed this.
